steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/neon-griffin-451814-n1/imgwebapp:v1', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/neon-griffin-451814-n1/imgwebapp:v1']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built"
    ls -la
    ls -al models/
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
      - "run"
      - "--filename=k8s/"
      - "--location=us-central1-a"
      - "--cluster=my-cluster"
      - "--image=gcr.io/neon-griffin-451814-n1/imgwebapp:v1"  # Ensure the correct image is deployed
      - "--namespace=default" # Optional: Specify namespace if needed
