apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      containers:
      - name: cv-app
        image: us-central1-docker.pkg.dev/neon-griffin-451814-n1/my-repo/imgwebapp:v1
        ports:
        - containerPort: 8501
